name: personal_health_tracker
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  charts_flutter: ^0.12.0
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^2.4.1
  dartz: 0.10.0
  equatable: ^2.0.5
  http: ^1.2.1
  go_router: ^14.1.4
  flutter_secure_storage: ^4.2.1
  shared_preferences: ^2.2.3
  dart_jsonwebtoken: ^2.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.10

flutter:
  uses-material-design: true

  # Adding assets section
  assets:
    - assets/images/logo.png
  
  fonts:
    - family: NotoSansEthiopic
      fonts:
        - asset: fonts/NotoSansEthiopic-Regular.ttf
    # - family: Roboto
    #   fonts:
    #     - asset: assets/fonts/Roboto-Regular.ttf
    #     - asset: assets/fonts/Roboto-Bold.ttf
    #       weight: 700  
